import type { UpgradeDefinition } from '../models/UpgradeDefinition';

export const UPGRADES: UpgradeDefinition[] = [
  {
    id: 'fire_rate',
    name: 'Fire Rate',
    description: '+10% shots/sec',
    baseCost: 25,
    costMultiplier: 1.35,
    maxLevel: 50,
    unlockLevel: 1,
    effect: (level) => ({ fireRateMultiplier: 1 + level * 0.10 }),
  },
  {
    id: 'damage',
    name: 'Damage',
    description: '+15% damage',
    baseCost: 30,
    costMultiplier: 1.40,
    maxLevel: 50,
    unlockLevel: 1,
    effect: (level) => ({ damageMultiplier: 1 + level * 0.15 }),
  },
  {
    id: 'knockback',
    name: 'Knockback',
    description: 'Push enemies back',
    baseCost: 50,
    costMultiplier: 1.50,
    maxLevel: 20,
    unlockLevel: 3,
    effect: (level) => ({ knockbackForce: level * 15 }),
  },
  {
    id: 'max_health',
    name: 'Fortify',
    description: '+20 max HP',
    baseCost: 40,
    costMultiplier: 1.30,
    maxLevel: 30,
    unlockLevel: 1,
    effect: (level) => ({ maxHealthBonus: level * 20 }),
  },
  {
    id: 'gold_bonus',
    name: 'Greed',
    description: '+10% gold',
    baseCost: 100,
    costMultiplier: 1.60,
    maxLevel: 25,
    unlockLevel: 5,
    effect: (level) => ({ goldMultiplier: 1 + level * 0.10 }),
  },
  {
    id: 'crit_chance',
    name: 'Critical Hit',
    description: '+3% crit chance',
    baseCost: 75,
    costMultiplier: 1.45,
    maxLevel: 20,
    unlockLevel: 7,
    effect: (level) => ({ critChance: Math.min(level * 0.03, 0.50) }),
  },
  {
    id: 'range',
    name: 'Scope',
    description: '+20 range',
    baseCost: 60,
    costMultiplier: 1.35,
    maxLevel: 15,
    unlockLevel: 4,
    effect: (level) => ({ rangeBonus: level * 20 }),
  },
  {
    id: 'regen',
    name: 'Repair',
    description: '+1 HP/5sec',
    baseCost: 150,
    costMultiplier: 1.55,
    maxLevel: 10,
    unlockLevel: 10,
    effect: (level) => ({ regenPerTick: level }),
  },
];
